spring:
  application:
    name: SpringReactiveServer
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect


weatherapi:
  host: https://api.weatherapi.com
  api-key: bf674e3c65f14e58b7d132104251911